### PR TITLE
Add some more common classes to default coverage config

### PR DESCRIPTION
**Pull request by russhwolf**

### CODE REVIEW

**Comment by ghost** [comment]
[46% (+46.28%) vs master 0%](https://ci.intrepid.io/job/Android/job/pull-requests/job/skeleton-android-pr/94/)

**Comment by justin-guan** [comment]
Are there any plans to add generated classes to the exclude list? For example, classes generated by data binding. Or is that out of scope for skeleton?

**Review by justin-guan — APPROVED** [review]

**Comment by russhwolf** [comment]
Generated code is included in a different part of the file since it should be excluded from all coverage reports, not just the unit test one. We have a line for Butterknife in there now since that's actually used here, but it probably wouldn't hurt to add data binding stuff too if you want to open a PR for it.

**Comment by ghost** [comment]
[46% (+46.28%) vs master 0%](https://ci.intrepid.io/job/Android/job/pull-requests/job/skeleton-android-pr/95/)

**Review by gdaniels — APPROVED** [review]

**Pull request merged**
